version: '3'

services:
  app:
    image: hwc9169/nasomedia-identity-service:latest
    ports:
      - "81:80"
    env_file:
      - .identity.env
    volumes:
      - .:/app:cached
    depends_on:
      - db
    command: >
      bash -c "/app/prestart.sh 
      && uvicorn app.main:app --host 0.0.0.0 --port 80"
    networks:
      servicenet:
        aliases:
          - identity
      internal:
    deploy:
      replicas: 1

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .identity.env
    networks:
      internal:
    deploy:
      replicas: 1

volumes:
  postgres-data:

networks:
  servicenet:
    external: true
  internal:
